apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: {app: bexhoma, component: sut, configuration: default, experiment: default}
  name: bexhoma-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: shared
---
apiVersion: v1
kind: Service
metadata:
  labels: {app: bexhoma, component: sut, configuration: default, experiment: default}
  name: bexhoma-sut
spec:
  #type: ClusterIP
  #clusterIP: None
  ports:
  - {port: 9091, protocol: TCP, name: port-dbms, targetPort: 5432}
  - {port: 9500, protocol: TCP, name: port-monitoring-application, targetPort: 9187}
  selector: {app: bexhoma, component: pool, configuration: default, experiment: default}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bexhoma-pool
  labels: {app: bexhoma, component: pool, configuration: default, experiment: default}
spec:
  replicas: 4
  selector:
    matchLabels: {app: bexhoma, component: pool, configuration: default, experiment: default}
  template:
    metadata:
      labels: {app: bexhoma, component: pool, configuration: default, experiment: default, pool: bexhoma-pool}
    spec:
      tolerations:
      #- key: "nvidia.com/gpu"
      #  effect: "NoSchedule"
      nodeSelector:
      #  kubernetes.io/hostname: cl-worker19
      containers:
      - name: pool
        image: edoburu/pgbouncer
        # connect via 'psql -U postgres -p 5432 -h localhost pgbouncer'
        # SHOW STATS;
        # SHOW POOLS;
        # SHOW CLIENTS;
        # SHOW SERVERS;
        # works: AUTH_TYPE scram-sha-256 with password postgres
        # works: AUTH_TYPE trust with empty password
        # https://www.pgbouncer.org/config.html
        # https://github.com/edoburu/docker-pgbouncer
        # https://github.com/farrajota/kubernetes-postgres-pgbouncer/blob/master/pgbouncer.yaml
        env: # https://github.com/edoburu/docker-pgbouncer/blob/master/entrypoint.sh
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: #postgres
        - name: DB_HOST
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['pool']
              #value: $(expr $BEXHOMA_SUT_NAME)
        - name: DB_PORT
          value: "9092"
        - name: AUTH_TYPE
          value: trust #scram-sha-256 #trust #md5 # scram-sha-256 # remove/comment this line if using postgres:13 and lower
        - name: POOL_MODE
          value: session # mode = transaction not working for YCSB
        - name: ADMIN_USERS
          value: postgres
        - name: DEFAULT_POOL_SIZE
          value: "32"
        - name: MIN_POOL_SIZE
          value: "4"
        - name: MAX_CLIENT_CONN
          value: "32"
        - name: LOG_CONNECTIONS
          value: "1"
        - name: LOG_DISCONNECTIONS
          value: "1"
        - name: LOG_POOLER_ERRORS
          value: "1"
        - name: LOG_STATS
          value: "1"
        - name: RESERVE_POOL_SIZE
          value: "16"
        #- name: MAX_PREPARED_STATEMENTS
        #  value: "256"
        #readinessProbe:
        #  exec:
        #    command:
        #    - pg_isready
        #    - -U
        #    - postgres
        #  initialDelaySeconds: 15
        #  periodSeconds: 60
        ports:
        - {containerPort: 5432}
        #resources:
        #  limits: {cpu: 16000m, memory: 128Gi}
        #  requests: {cpu: 4000m, memory: 4Gi}
        #  #, ephemeral-storage: "1536Gi"}
---
apiVersion: v1
kind: Service
metadata:
  labels: {app: bexhoma, component: pool, configuration: default, experiment: default}
  name: bexhoma-pool
spec:
  ports:
  - {port: 9092, protocol: TCP, name: port-dbms, targetPort: 5433}
  - {port: 9300, protocol: TCP, name: port-monitoring, targetPort: 9300}
  selector: {app: bexhoma, component: sut, configuration: default, experiment: default}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {app: bexhoma, component: sut, configuration: default, experiment: default}
  name: bexhoma-deployment-postgres
spec:
  replicas: 1
  selector:
    matchLabels: {app: bexhoma, component: sut, configuration: default, experiment: default}
  template:
    metadata:
      labels: {app: bexhoma, component: sut, configuration: default, experiment: default}
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
      - {name: dockerhub}
      nodeSelector:
      #  kubernetes.io/hostname: cl-worker11
      tolerations:
      #- key: "nvidia.com/gpu"
      #  effect: "NoSchedule"
      terminationGracePeriodSeconds: 180
      containers:
      - name: dbms
        image: postgres:17.5
        env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: PGPORT
          value: "5433" # remove/comment this line for default ports
        # pg_ctl: cannot be run as root
        lifecycle:
          #postStart:
          #  exec:
          #    command: ["/bin/sh", "-c", "echo 'Hello from the postStart handler' > /usr/share/message && cat /usr/share/message"]
          preStop:
            exec:
              #command: ["/bin/sh", "-c", "gosu postgres pg_ctl stop -D /var/lib/postgresql/data -m fast"]
              #command: ["/bin/sh", "-c", "gosu postgres pg_ctl stop -m fast"]
              #command: ["echo 'PRESTOP' ;", "/bin/sh", "-c", "gosu postgres pg_ctl stop -m smart -t 120"]
              #command: ["/bin/sh", "-c", "echo 'Hello from the preStop handler'; gosu postgres pg_ctl stop -m smart -t 120"]
              #command: ["gosu postgres", "pg_ctl stop -m smart -t 120"]
              #command: ["/bin/sh", "-c"]
              #args: ["gosu postgres pg_ctl stop -m smart -t 120"]
              #command: ["/bin/sh", "-c", "gosu postgres 'pg_ctl stop -m smart -t 120'"]
              #command: ["/bin/sh", "-c", "gosu postgres '/usr/lib/postgresql/16/bin/pg_ctl stop -m smart -t 120'"]
              #command: ["/bin/sh -c 'gosu postgres /usr/lib/postgresql/16/bin/pg_ctl stop -m smart -t 120'"]
              command: ["/bin/sh", "-c", "gosu postgres /usr/lib/postgresql/16/bin/pg_ctl stop -m smart -t 120"]
              #command: ["/bin/sh", "-c", "echo 'Hello from the preStop handler' > /usr/share/message && cat /usr/share/message"]
        #command: ["sh", "-c", "trap 'gosu postgres pg_ctl stop -m smart' SIGTERM; gosu postgres postgres"] # trap: SIGTERM: bad trap
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
            - -p
            - "5433"
          initialDelaySeconds: 15
          periodSeconds: 60
        ports:
        - {containerPort: 5433}
        securityContext:
          allowPrivilegeEscalation: false
          #runAsNonRoot: true
          #runAsUser: 1000
          #runAsGroup: 1000
          #capabilities:
          #  drop:
          #    - ALL
          #readOnlyRootFilesystem: true #could not create lock file "/var/run/postgresql/.s.PGSQL.5432.lock": Read-only file system
        resources:
          limits: {cpu: 16000m, memory: 128Gi}
          requests: {cpu: 1000m, memory: 1Gi}
          #, ephemeral-storage: "1536Gi"}
        volumeMounts:
        - {mountPath: /data, name: benchmark-data-volume}
        - {mountPath: /dev/shm, name: dshm}
        - {mountPath: /var/lib/postgresql/data, name: benchmark-storage-volume}
        args: [
          "-c", "max_worker_processes=64",
          "-c", "max_parallel_workers=64",
          "-c", "max_parallel_workers_per_gather=64",
          "-c", "max_parallel_maintenance_workers=64", # only for PostgreSQL > 10 (?)
          "-c", "max_wal_size=32GB",
          "-c", "shared_buffers=64GB",
          #"-c", "shared_memory_size=32GB", # read-only
          "-c", "max_connections=2048",
          "-c", "autovacuum_max_workers=10",
          "-c", "autovacuum_vacuum_cost_limit=3000",
          "-c", "vacuum_cost_limit=1000",
          "-c", "checkpoint_completion_target=0.9",
          "-c", "cpu_tuple_cost=0.03",
          "-c", "effective_cache_size=64GB",
          "-c", "maintenance_work_mem=2GB",
          #"-c", "max_connections=1700",
          #"-c", "random_page_cost=1.1",
          "-c", "wal_buffers=1GB",
          "-c", "work_mem=32GB",
          #"-c", "huge_pages=on",
          "-c", "temp_buffers=4GB",
          "-c", "autovacuum_work_mem=-1",
          "-c", "max_stack_depth=7MB",
          "-c", "max_files_per_process=4000",
          "-c", "effective_io_concurrency=32",
          "-c", "wal_level=minimal",
          "-c", "max_wal_senders=0",
          "-c", "synchronous_commit=off",
          "-c", "checkpoint_timeout=1h",
          "-c", "checkpoint_warning=0",
          "-c", "autovacuum=off",
          "-c", "max_locks_per_transaction=64",
          "-c", "max_pred_locks_per_transaction=64",
          "-c", "default_statistics_target=1000",
          "-c", "random_page_cost=60"
        ]
        # , "-c", "listen_addresses='*'", "-c", "logging_collector=on"
        # , "-c", "pg_stat_statements.save=off", "-c", "pg_stat_statements.track=all", "-c", "shared_preload_libraries='pg_stat_statements'"
      - name: monitor-application
        image: quay.io/prometheuscommunity/postgres-exporter:v0.17.1 #v0.15.0
        command: ["postgres_exporter"] #, "--auto-discover-databases"]
        env:
          - name: DATA_SOURCE_URI
            value: "localhost:5432/?sslmode=disable"
          - name: DATA_SOURCE_USER
            value: "postgres"
          - name: DATA_SOURCE_PASS
            value: ""
          #- name: PG_EXPORTER_AUTO_DISCOVER_DATABASES
          #  value: "true"
          #- name: DATA_SOURCE_URI
          #  value: "postgresql://user:password@/postgres?host=/var/run/postgresql"
        ports:
          - containerPort: 9187
        resources:
          requests: {cpu: 1000m, memory: 4Gi}
          limits: {cpu: 1000m, memory: 4Gi}
      volumes:
      - name: benchmark-data-volume
        persistentVolumeClaim: {claimName: bexhoma-data}
      - name: benchmark-storage-volume
        persistentVolumeClaim: {claimName: bexhoma-storage}
      - name: rootfs
        hostPath:
          path: /
      - name: var-run
        hostPath:
          path: /var/run
      - name: sys
        hostPath:
          path: /sys
      - name: docker
        hostPath:
          path: /var/lib/docker
      - name: disk
        hostPath:
          path: /dev/disk
      - name: dshm
        emptyDir:
          medium: Memory
